### ISSUE TITLE
Flip a tableview on an x or y axis?

### ISSUE THREAD

**Issue by daviddelmonte** [mergesort/TableFlip#11]
Hi, great control. Thank You! Is it possible to do the above?

**Comment by mergesort** [comment]
Hey @daviddelmonte. I'm not sure what you're asking exactly, would you be able to go into more depth so I can try and help?

Thanks!

**Comment by daviddelmonte** [comment]
Surely. I've a tableview that has different layouts based on some buttons. When I tap a button, I would love the tableview to flip on it's horizontal or vertical axis. While it flips, I would swap layouts. Thanks for the fast response.

**Comment by mergesort** [comment]
Hey @daviddelmonte. The library is built to create temporal animations, not specific more permanent layouts for `UITableView`, after calling `reloadData()`, to give you animations which can be crash-free without mucking around in `insertRow`/`deleteRow` method calls.

If you wish to achieve rotation of your `UITableView`, I would recommend using the `UITableView`s transform property to actually flip the `UITableView` from one axis to another (so it's pretending to be vertical while the screen is horizontal), or vice versa.

If you want to do that with the library, you can actually pass in your own animation using the `TableViewAnimation.Table.custom(duration: TimeInterval, transform: CGAffineTransform, options: UIViewAnimationOptions)` case, and pass in your own transform.

Does that help answer the question? I'm still not quite 100% sure I know, or have the solution you're looking for in the scope of the library.

Thanks!

**Comment by daviddelmonte** [comment]
OK. I can look at the tableview transform. Thanks again! I'm still using the control in another instance!
