### ISSUE TITLE
how can i use this  after i pod this into my project?

### ISSUE THREAD

**Issue by fonglaaaam** [mergesort/TableFlip#3]
i use it in an ObjectC project

**Comment by mergesort** [comment]
Hey @fonglaaaam. TableFlip is very heavily built on Swift-style enums, so I didn't have plans to back port it to Objective-C, but might consider adding an Objective-C API if there's enough of a demand for it.

**Comment by mergesort** [comment]
I'm going to close this out for now, and wait to hear if more people request Objective-C compatibility. Thanks for the suggestion!
