### ISSUE TITLE
Cannot convert type TableViewAnimation.Cell to expected TableViewAnimation.Table

### ISSUE THREAD

**Issue by JaDenis** [mergesort/TableFlip#6]
How do I animate each cell ?
`self.tableView.animateTableView(animation: TableViewAnimation.Cell.fade(duration: 0.8), completion: nil)`

gives me an error, since animateTableView is waiting for TableViewAnimation.Table

**Comment by mergesort** [comment]
You're almost there. Instead of calling `animateTableView`, you need to call `animateCells`, when you're passing in a `Cell` animation.

Your call should end up looking like this:

```self.tableView.animateCells(animation: TableViewAnimation.Cell.fade(duration: 0.8))```

Let me know if that works for you.

**Comment by JaDenis** [comment]
thanks a lot, sorry for making a fuss 👍
looks so good :)

**Comment by mergesort** [comment]
Thanks! Enjoy.
