### ISSUE TITLE
Readme presentation

### ISSUE THREAD

**Issue by TofPlay** [mergesort/TableFlip#7]
Hi,
Interesting component 🙂
Here is a template to help you improve your readme: [iOS-readme-template](https://github.com/TofPlay/iOS-readme-template)

**Comment by mergesort** [comment]
Thanks for the suggestion @TofPlay. I added badges and requirements in this [commit]( https://github.com/mergesort/TableFlip/commit/9f7e8d5e0ca12240623bec6d97d891c474fc0930) to match the template.

**Comment by mergesort** [comment]
I'm going to close this out since I made the change and it seems to be in line with what the template asks for.
