### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by TofPlay** [mergesort/TableFlip#8]
Hi,
For iOS and macOS projets it's will be great to make your component [Carthage](https://github.com/Carthage/Carthage) compatible

Take a look at these articles: 
- [Ruthlessly Simple Dependency Management with Carthage](https://bit.ly/2IWvGks)
- [Carthage Tutorial: Getting Started](https://bit.ly/2zes4dN)
- [Making Carthage-compatible Frameworks with Swift](https://bit.ly/2tXUofp)
- [Swift Cross Platform Framework](https://bit.ly/2ysgETA) (section [Configure targets for Carthage](https://bit.ly/2tZUOSt)) 👍

On your `README.md` add [![Carthage compatible](https://img.shields.io/badge/Carthage-Compatible-brightgreen.svg?style=flat)](https://github.com/Carthage/Carthage)  on top and add section for the installation with Carthage.

**Comment by mergesort** [comment]
Hey @TofPlay. This is a bit delayed, but if you'd like to add Carthage support, I'd be happy to add it in.

Thanks!

**Comment by mergesort** [comment]
I'm going to close this out due to no expressed interest. If someone else comes across this and wants to add support, by all means do, and I'll gladly accept a PR.
